apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "b_log.fullname" . }}-worker
  labels:
    {{- include "b_log.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "b_log.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "b_log.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: wait-dns-pg
          image: postgres:16
          command: ["bash","-c"]
          args:
            - >
              H="{{ include "b_log.postgresql.host" . }}.{{ .Release.Namespace }}.svc.cluster.local";
              for i in $(seq 1 150); do
                getent hosts "$H" >/dev/null 2>&1 &&
                pg_isready -h "$H" -p 5432 >/dev/null 2>&1 && exit 0;
                echo "waiting for postgres at $H:5432 ($i/150)";
                sleep 2;
              done;
              echo "postgres did not become ready in time"; exit 1
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy | default "IfNotPresent" }}
          env:
            - name: DATABASE_URL
              value: {{ printf "postgres://%s?sslmode=disable" (include "b_log.postgresql.conn" .) | quote }}
            - name: NATS_URL
              value: {{ printf "nats://%s:4222" (include "b_log.nats.host" .) | quote }}
            - name: JS_DOMAIN
              value: {{ .Values.nats.config.merge.jetstream.domain | default "prod" | quote }}
            - name: SHARED_DIR
              value: {{ .Values.uploads.mountPath | quote }}
          volumeMounts:
            {{- if .Values.uploads.pvc.enabled }}
            - name: uploads
              mountPath: {{ .Values.uploads.mountPath | quote }}
            {{- end }}
      volumes:
        {{- if .Values.uploads.pvc.enabled }}
        - name: uploads
          persistentVolumeClaim:
            claimName: {{ .Values.uploads.pvc.name }}
        {{- end }}
